apiVersion: v2
name: app-translator
description: Application for translating text with multiple languages
type: application
version: 2.0.0
appVersion: "2.0.0"

dependencies:
  - name: postgresql
    version: "18.5.1"
    repository: "https://charts.bitnami.com/bitnami"
