backend:
  image: sara3259/app-translator-backend:latest
  replicas: 2
  port: 3001

frontend:
  image: sara3259/app-translator-frontend:latest
  replicas: 2
  port: 80

translator:
  image: libretranslate/libretranslate:latest
  replicas: 1
  port: 5000
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

database:
  name: translations
  user: postgres
  password: postgres
  storage: 10Gi

ingress:
  enabled: true
  host: translator.local
